### ISSUE TITLE
STA9750 Dani-0000 MiniProject #00

### ISSUE THREAD

**Issue by Dani-0000** [Dani-0000/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://dani-0000.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @Dani-0000 !

Peer Feedback:

- @Haina0
- @chricannon
- @camilomartinez777

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @Dani-0000.

Website URL should be: https://Dani-0000.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @Dani-0000 and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by camilojourney** [comment]
Hi Dani, I hope you are doing great. I like the page. It's straight to the point. I suggest adding more things about you; I am sure there are many exciting things you can tell about and show to the world.

The best!

**Comment by Haina0** [comment]
Hi @Dani-0000 great job getting your website up and running, I look forward to seeing what you add to it throughout the rest of the course.

**Comment by chricannon** [comment]
Hi Dani! 

Your website functions properly. I like how you italicized your name. One suggestion would be to add an "About Me" section. 

Great job!
