### ISSUE TITLE
STA9750 Dani-0000 MiniProject #01

### ISSUE THREAD

**Issue by Dani-0000** [Dani-0000/STA9750-2024-FALL#3]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #01 - check it out!

[Fiscal Characteristics of Major US Public Transit Systems – STA 9750 2024 Submission Material.pdf](https://github.com/user-attachments/files/17142339/Fiscal.Characteristics.of.Major.US.Public.Transit.Systems.STA.9750.2024.Submission.Material.pdf)

**Comment by michaelweylandt** [comment]
Thanks @Dani-0000 !

Peer Feedback:

- @chricannon
- @jasonamey
- @nikitagtm
- @YantingZhao11

It is now time for the peer feedback round for Mini-Project #01. Please
review @Dani-0000's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric,
please grade their submission out of a total of 50 points.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @Dani-0000, but you are of course
welcome to initiate a discussion.

@Dani-0000: please engage fully with your peers. They are here to help you!

Submission URL should be: https://Dani-0000.github.io/STA9750-2024-FALL/mp01.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by Dani-0000** [comment]
Here is the updated link:
 https://dani-0000.github.io/STA9750-2024-FALL/MP01.html

**Comment by nikitagtm** [comment]
Congratulations Dani-000 for completing your MINI#01.

Things I Like:

1. Clear introduction and structure: The report effectively introduces the purpose of the analysis, focusing on the farebox recovery ratio and its significance.
2. Answers the questions given.

Things to Improve:

1. Using bold or headings for key questions and findings would improve the readability of the report, helping the reader navigate the analysis more easily.
3. Instead of displaying the entire tibble output like this, It would be more efficient to directly show the result as a statement.
 ```
 A tibble: 1 × 4
  Mode       month      Agency                    Unlinked_Passenger_Trips
  <chr>      <date>     <chr>                                        <dbl>
```
3. It would enhance the report if the conclusions and key findings were highlighted more prominently after addressing each question, providing a clear summary and emphasizing the main insights from the analysis.

4. You can use **slice(1)** in the code to modify the output to return just the top result instead of displaying all rows-
 ```
   Mode                        sum_Vehicle_Revenue_Miles_Mode
   <chr>                                                <dbl>
 1 Bus                                            49444494088
 2 Demand Response                                17955073508
 3 Heavy Rail                                     14620362107
 4 Commuter Rail                                   6970644241
 5 Vanpool                                         3015783362
 6 Light Rail                                      2090094714
 7 Commuter Bus                                    1380948975
 8 Publico                                         1021270808
 9 Trolleybus                                       236840288
10 Bus Rapid Transit                                118425283
11 Ferryboat                                         65589783
12 Streetcar Rail                                    63389725
13 Monorail Automated Guideway                       37879729
14 Hybrid Rail                                       37787608
15 Alaska Railroad                                   13833261
16 Cable Car                                          7386019
17 Inclined Plane                                      705904
18 Aerial Tramway 
```

Rating: 
Written Communication: 8.5/10
Project Skeleton: 9/10
Formatting & Display: 8/10
Code Quality: 9/10
Data Presentation: 10/10
Total: 44.5/50

**Comment by YantingZhao11** [comment]
Hi @Dani-0000,

Please see the feedback below:

Written Communication: 7.5/10
Your introduction is clear, but highlighting key insights in your conclusions would enhance the impact.

Project Skeleton: 8.5/10
A few more headings could help readers navigate even better.

Formatting & Display: 7.5/10
Using bold for important points would improve readability, and summarizing outputs would streamline your report.

Code Quality: 8/10
Your code runs smoothly, but consider making the output more concise by using methods like slice(1) for clarity.

Data Preparation: 10/10

Total Score: 41.5/50

Best,
Yanting

**Comment by chricannon** [comment]
Hi @Dani-0000! 

Great job on this project. You successfully completed all tasks, your site is easy to read and follow, and your code properly executes. 

Written Communication: 9/10. Including a conclusion heading and paragraph at the end of the page would help tie things up. 

Project Skeleton: 9/10. Adding a few more headings and breaking up the paragraphs into smaller paragraphs may help the reader flow through the project better. 

Formatting & Display: 9/10. Perhaps importing some packages to have the ability to modify your table output to look more like a table, with outlines and column headings, would make the formatting even better. This is something I hope to learn how to do myself, so just an idea! 

Code Quality: 10/10. Your code executes properly and answers each question. 

Data Preparation: 10/10 (Automatic)

Total: **47/50** Great job!

**Comment by charles-ramirez** [comment]
Hi @jasonamey, 

This is just a reminder that your peer review is due today at 11:45 pm.

**Comment by jasonamey** [comment]
Hi @Dani-0000,

Written Communication **10/10**
Your narrative for this assignment is very thorough and convincingly explained.  There is some strong writing in your narrative as well.  I  do think you can round your decimals to 3 or 4 places. 

> Vanpool maintained the lowest expenses per Vehicle Revenue Mile (VRM) with a total of 0.3366857

> Vanpool maintained the lowest expenses per Vehicle Revenue Mile (VRM) with a total of 0.337.


Project Skeleton **10/10** 
As far as I can tell, you complete all components of the assignment. And all the components are convincingly explained. 

Formatting and Display **7/10** 
I look into a a strategy beyond printing out dataframes and tibbles. 

I'd be consistent with your title casing here (either make the "s" uppercase, or make everything else lowercase): 
`summarize(sum_Vehicle_Revenue_Miles_Mode = sum(Vehicle_Revenue_Miles))`

Code Quality **10/10**
I think it's great you added comments in your code. 

I like that you narrated your print statement here : 
`print(paste("Ridership fall: ", ridership_fall))`

Data Preparation **10/10** 

I think this is a real solid project. **47/50**
